Tasks 51 60
dudzon/ui-internship-lwo2 pull request #6
Opened 2019-05-02 08:08 UTC by dudzon

2019-05-06 11:06 UTC, tkachukivan requested changes

2019-05-06 11:06 UTC, tkachukivan commented on tasks/53_diff-array/diff-array.js
> +//     if (arr2.indexOf( item ) === -1) {
Just FYI also you can have solution in this style but using `Set`, it will looks simpler and without `indexOf` method, which here is better to change to `includes`

2019-05-06 11:06 UTC, tkachukivan commented on tasks/54_roman-numbers-convert/roman-numbers-convert.js
> +      romanNumber += Object.keys( romanLetters )[i];
you can move `Object.keys` out of loop as it will always return the same result no reason to call it for every loop iteration. Also you can use `forEach` on `valueArr` instead of `for in` and anyway getting by index value from array

Also you `for in` only for iterate object properties

2019-05-06 11:06 UTC, tkachukivan commented on tasks/57_pig-latin/pig-latin.js
> +  const isAVowel = str[0].match( /[aeiou]/g );
you don't need /g flag here as you are testing just one symbol, also you can use test method as after you don't work with result of regexp, and as you use this regexp twice you can create a variable for this regexp

2019-05-06 11:06 UTC, tkachukivan commented on tasks/58_missed-letters/missed-letters.js
> +      return String.fromCharCode( str[i + 1].charCodeAt() - 1 );
it probably will a bit easier to understand what is going on at first look if change `str[i + 1].charCodeAt() - 1` to `str[i].charCodeAt() + 1`

2019-05-06 11:06 UTC, tkachukivan commented on tasks/60_convert-html-entities/convert-html-entities.js
> +  for ( let key in entities) {
`for of` or `forEach` will looks better, use `for in` only for iterating object properties but not arrays

also you can have solve it with using map(or simple object) where as key you will have sign and entity as value of this key, also here you can pass to replace function and just take symbol which was matched from your map

2019-05-07 12:17 UTC, asmyk approved these changes

2019-05-07 12:17 UTC, asmyk commented on tasks/52_sum-all-numbers-in-range/sum-all-numbers-in-range.js
> +  return sum;
just FYI - you can solve this without Math functions in one loop. Just think if you really need to loop from minimum to maximum.

2019-05-07 12:17 UTC, asmyk commented on tasks/57_pig-latin/pig-latin.js
> +      break;
are u sure about that you need a 'break' instruction here?

2019-05-14 08:56 UTC, dudzon commented on tasks/53_diff-array/diff-array.js
> +//     if (arr2.indexOf( item ) === -1) {
Done

2019-05-14 09:26 UTC, dudzon commented on tasks/57_pig-latin/pig-latin.js
> +  const isAVowel = str[0].match( /[aeiou]/g );
Done

2019-05-14 09:47 UTC, dudzon commented on tasks/54_roman-numbers-convert/roman-numbers-convert.js
> +      romanNumber += Object.keys( romanLetters )[i];
Done, but I'm not sure if you want me to move `Object.keys` out of `while` loop. It doesn't work in this case.

2019-05-14 10:16 UTC, tkachukivan commented on tasks/54_roman-numbers-convert/roman-numbers-convert.js
> +      romanNumber += Object.keys( romanLetters )[i];
strange, why it is not fork as it should work

```
let romanLettersKeys = Object.keys(romanLetters)

romanNumber += romanLettersKeys[i];
```

2019-05-14 10:17 UTC, tkachukivan approved these changes

2019-05-14 10:36 UTC, dudzon commented on tasks/54_roman-numbers-convert/roman-numbers-convert.js
> +      romanNumber += Object.keys( romanLetters )[i];
👍  silly me :)

2019-05-14 10:37 UTC, merged